language: node_js
script: npm test
after_success:
    # "curl --ftp-create-dirs -T * -u $ftp_user:$ftp_password ftp://arakneedebiyat.com/"
    "find . -type f -exec curl -u $ftp_user:$ftp_password --ftp-create-dirs -T {} ftp://arakneedebiyat.com/{} \;"
